name: Daily Timestamp and Date Commit

on:
  schedule:
    - cron: '0 1,10,19 * * *'  # Runs every day at 00:00 and 12:00 UTC
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  update_timestamp_and_date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp and date file
        run: |
          TIMESTAMP=$(date +%s)  # Get Unix timestamp
          HUMAN_DATE=$(date +'%Y-%m-%d %H:%M:%S') # Get human-readable date
          echo "$TIMESTAMP" > timestamp.txt
          echo "$HUMAN_DATE" > date.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "ebricca@me.com"
          git config --local user.name "ebricca"
          git add timestamp.txt date.txt
          git commit -m "Daily timestamp and date update: $(date +'%Y-%m-%d %H:%M:%S')"

          # Authenticate using the PAT
          git remote set-url origin "https://${{ secrets.PA_WF_TK2 }}@github.com/${{ github.repository }}"

          git push origin main